const QUESTION_SV = {
  OVERALL_CONDITION: {
    DOES_THE_UNIT_HAVE_TWO_KEYS_WITH_FOBS_AVAILABLE: null,
    IS_THE_UNIT_EXTERIOR_CLEAN: null,
    IS_THE_INTERIOR_FREE_OF_STRONG_ODORS: null,
    IS_THE_UNIT_INTERIOR_CLEAN_AND_FREE_OF_RUBBISH: null,
  },
  DRIVER_DOOR: {
    IS_DOOR_OPERATIONAL: null,
    IS_DOOR_FRAME_FREE_OF_CRACKS_AT_HINGE_OR_OTHER_ATTACHMENT_POINT: null,
    IS_DOOR_STRAP_INTACT: null,
  },
  DRIVER_MIRROR: { IS_THE_MARKER_SIGNAL_LAMP_OPERABLE: null },
  HOOD: { DOES_HOOD_OPERATE_FREELY: null },
  LIGHTS: {
    DO_HEADLIGHTS_ILLUMINATE: null,
    DO_MARKER_LIGHTS_ILLUMINATE: null,
  },
  BUMPER: { IS_LICENSE_PLATE_INSTALLED_IF_APPLICABLE: null },
  PASSENGER_MIRROR: { IS_THE_MARKER_SIGNAL_LAMP_OPERABLE: null },
  PASSENGER_DOOR_EXTERIOUR: {
    IS_DOOR_OPERATIONAL: null,
    IS_DOOR_FRAME_FREE_OF_CRACKS_AT_HINGE_OR_OTHER_ATTACHMENT_POINT: null,
    IS_DOOR_STRAP_INTACT_RAM_ONLY: null,
  },
  RH_BODY_PANEL: { IS_THE_AMAZON_BRANDING_FREE_OF_DAMAGE: null },
  TAIL_LIGHTS: { ARE_THE_BULBS_OPERATIONAL: null },
  REAR_STEP: {
    IS_THE_RH_STEP_PRESENT: null,
    IS_THE_STEP_FREE_FROM_DAMAGE: null,
    ARE_THE_STEP_END_CAPS_INTACT: null,
  },
  LICENSE_PLATE: { IS_LICENSE_PLATE_INSTALLED: null },
  DRIVER_COCKPIT: {
    DOES_VEHICLE_START: null,
    IS_THE_VEHICLE_RUNNING_SMOOTHLY: null,
    IS_THE_DASHBOARD_FREE_OF_ANY_WARNING_LIGHTS: null,
    IS_INSTRUMENT_CLUSTER_FREE_OF_DAMAGE: null,
    IS_STEERING_WHEEL_FREE_OF_DAMAGE: null,
    IS_PARKING_BRAKE_OPERATIONAL: null,
    IS_THE_REAR_VIEW_CAMERA_OPERATIONAL: null,
    IS_THE_NETRADYNECAMERATELEMATICS_DEVICE_SECURE: null,
    IS_SEAT_BELT_FREE_OF_DAMAGE: null,
    DOES_SEAT_BELT_PROPERLY_BUCKLE: null,
    IS_DRIVER_SEAT_FREE_OF_DAMAGE: null,
    IS_AREA_CLEAN: null,
    IS_VEHICLE_REGISTRATION_IN_VEHICLE: null,
    IS_SAFETY_KIT_PRESENT: null,
  },
  PASSENGER_AREA: {
    IS_SEAT_BELT_FREE_OF_DAMAGE: null,
    DOES_SEAT_BELT_PROPERLY_BUCKLE: null,
    IS_DRIVER_SEAT_FREE_OF_DAMAGE: null,
    IS_AREA_CLEAN: null,
    ARE_THE_INTERIORS_FREE_OF_ANY_OBVIOUS_DAMAGE: null,
    IS_THE_CABIN_FREE_OF_ANY_SMOKE_ODORS: null,
  },
  DIVIDER_DOOR: {
    IS_THE_DIVIDER_DOOR_OPERATIONAL: null,
    DOES_THE_DOOR_LATCH_OPEN: null,
    DOES_THE_DOOR_LATCH_CLOSE: null,
  },
  CARGO_AREA: {
    ARE_CARGO_SHELVES_PRESENT: null,
    IS_THE_CARGO_AREA_FREE_OF_DAMAGE: null,
    IS_THE_AREA_CLEAN: null,
    ARE_INTERIOR_LIGHTS_OPERATIONAL: null,
    IS_WHEEL_DOLLY_PRESENT: null,
    IS_SPARE_TIRE_PRESENT_CDV_SV_ONLY: null,
  },
  FRAME__STRUCTURAL__UNIBODY: {
    IS_THE_STRUCTURE_OR_UNIBODY_FREE_OF_ANY_OBVIOUS_DAMAGE: null,
  },
  EXHAUST_SYSTEM: {
    IS_THE_EXHAUST_SYSTEM_FREE_ANY_EXHAUST_LEAKS_OR_DAMAGE: null,
  },
  ENGINE_OR_MECHANICAL_DAMAGE: {
    IS_THE_ENGINE_FREE_OF_ANY_MECHANICAL_DAMAGES: null,
  },
  ELECTRICAL: {
    ARE_ALL_THE_ELECTRICAL_EQUIPMENT_AND_ACCESSORIES_OPERABLE: null,
  },
};

export default QUESTION_SV;
