const CF_NA_ACTION = {
  OVERALL_CONDITION: { IS_THE_INTERIOR_FREE_OF_STRONG_ODORS: null },
  DIVIDER_DOOR: { IS_THE_DIVIDER_DOOR_OPERATIONAL: null },
  LIGHTS: {
    DO_HEADLIGHTS_ILLUMINATE: null,
    DO_MARKER_LIGHTS_ILLUMINATE: null,
  },
  BUMPER: { IS_LICENSE_PLATE_INSTALLED_IF_APPLICABLE: null },
  DIVIDER_DOOR: { IS_THE_DIVIDER_DOOR_OPERATIONAL: null },
  RH_CARGO_DOOR: { DOES_THE_DOOR_OPERATE_SMOOTHLY_AND_CORRECT__CV_ONLY: null },
  RH_REAR_DOOR: { IS_DOOR_OPERATIONAL_CV_ONLY: null },
  ROLLUP_DOOR: { IS_DOOR_OPERATIONAL_CV_CDV_ONLY: null },
  TAIL_LIGHTS: { ARE_THE_BULBS_OPERATIONAL: null },
  REAR_STEP: { IS_THE_RH_STEP_PRESENT: null },
  SPARE_TIRE: { IS_THE_SPARE_TIRE_PRESENT_CV_ONLY: null },
  LICENSE_PLATE: { IS_LICENSE_PLATE_INSTALLED: null },
  DRIVER_COCKPIT: {
    DOES_VEHICLE_START: null,
    IS_THE_VEHICLE_RUNNING_SMOOTHLY: null,
    IS_PARKING_BRAKE_OPERATIONAL: null,
    IS_THE_REAR_VIEW_CAMERA_OPERATIONAL: null,
    DOES_SEAT_BELT_PROPERLY_BUCKLE: null,
    IS_VEHICLE_REGISTRATION_IN_VEHICLE: null,
    IS_SAFETY_KIT_PRESENT: null,
  },
  PASSENGER_AREA: {
    IS_THE_CABIN_FREE_OF_ANY_SMOKE_ODORS: null,
    DOES_SEAT_BELT_PROPERLY_BUCKLE: null,
  },
  DIVIDER_DOOR: { DOES_THE_DOOR_LATCH_OPEN: null },
  CARGO_AREA: { IS_WHEEL_DOLLY_PRESENT: null },
  ENGINE_OR_MECHANICAL_DAMAGE: {
    IS_THE_ENGINE_FREE_OF_ANY_MECHANICAL_DAMAGES: null,
  },
  ELECTRICAL: {
    ARE_ALL_THE_ELECTRICAL_EQUIPMENT_AND_ACCESSORIES_OPERABLE: null,
  },
};

export default CF_NA_ACTION;
