const CF_R_QUESTION = {
  OVERALL_CONDITION: {
    DOES_THE_UNIT_HAVE_TWO_KEYS_WITH_FOBS_AVAILABLE: null,
    IS_THE_UNIT_EXTERIOR_CLEAN: null,
    IS_THE_UNIT_INTERIOR_CLEAN_AND_FREE_OF_RUBBISH: null,
  },
  DRIVER_DOOR: {
    IS_DOOR_FRAME_FREE_OF_CRACKS_AT_HINGE_OR_OTHER_ATTACHMENT_POINT: null,
    IS_DOOR_STRAP_INTACT: null,
  },
  DRIVER_MIRROR: { IS_THE_MARKER_SIGNAL_LAMP_OPERABLE: null },
  HOOD: { DOES_HOOD_OPERATE_FREELY: null },
  PASSENGER_MIRROR: { IS_THE_MARKER_SIGNAL_LAMP_OPERABLE: null },
  PASSENGER_DOOR_EXTERIOUR: {
    IS_DOOR_FRAME_FREE_OF_CRACKS_AT_HINGE_OR_OTHER_ATTACHMENT_POINT: null,
    IS_DOOR_STRAP_INTACT_RAM_ONLY: null,
  },
  STEP: {
    IS_THE_RH_STEP_PRESENT_CV_ONLY: null,
    IS_THE_STEP_FREE_FROM_DAMAGE_CV_ONLY: null,
    ARE_THE_STEP_END_CAPS_INTACT_CV_ONLY: null,
  },
  RH_BODY_PANEL: { IS_THE_AMAZON_BRANDING_FREE_OF_DAMAGE: null },
  RH_REAR_DOOR: {
    IS_DOOR_FRAME_FREE_OF_CRACKS_AT_HINGE_OR_OTHER_ATTACHMENT_POINT_CV_ONLY:null,
    IS_DOOR_STRAP_INTACT_CV_ONLY: null,
  },
  LH_REAR_DOOR: {
    IS_DOOR_OPERATIONAL_CV_ONLY: null,
    IS_DOOR_FRAME_FREE_OF_CRACKS_AT_HINGE_OR_OTHER_ATTACHMENT_POINT_CV_ONLY:
      null,
    IS_DOOR_STRAP_INTACT_CV_ONLY: null,
  },
  REAR_STEP: {
    IS_THE_STEP_FREE_FROM_DAMAGE: null,
    ARE_THE_STEP_END_CAPS_INTACT: null,
  },
  DRIVER_COCKPIT: {
    IS_THE_DASHBOARD_FREE_OF_ANY_WARNING_LIGHTS: null,
    IS_INSTRUMENT_CLUSTER_FREE_OF_DAMAGE: null,
    IS_STEERING_WHEEL_FREE_OF_DAMAGE: null,
    IS_THE_NETRADYNECAMERATELEMATICS_DEVICE_SECURE: null,
    IS_SEAT_BELT_FREE_OF_DAMAGE: null,
    IS_DRIVER_SEAT_FREE_OF_DAMAGE: null,
    IS_AREA_CLEAN: null,
  },
  PASSENGER_AREA: {
    IS_SEAT_BELT_FREE_OF_DAMAGE: null,
    IS_DRIVER_SEAT_FREE_OF_DAMAGE: null,
    IS_AREA_CLEAN: null,
    ARE_THE_INTERIORS_FREE_OF_ANY_OBVIOUS_DAMAGE: null,
  },
  DIVIDER_DOOR: {
    IS_THE_DIVIDER_DOOR_OPERATIONAL: null,
    DOES_THE_DOOR_LATCH_CLOSE: null,
  },
  CARGO_AREA: {
    ARE_CARGO_SHELVES_PRESENT: null,
    IS_THE_CARGO_AREA_FREE_OF_DAMAGE: null,
    IS_THE_AREA_CLEAN: null,
    ARE_INTERIOR_LIGHTS_OPERATIONAL: null,
  },
  FRAME__STRUCTURAL__UNIBODY: {
    IS_THE_STRUCTURE_OR_UNIBODY_FREE_OF_ANY_OBVIOUS_DAMAGE: null,
  },
  EXHAUST_SYSTEM: {
    IS_THE_EXHAUST_SYSTEM_FREE_ANY_EXHAUST_LEAKS_OR_DAMAGE: null,
  },
};

export default CF_R_QUESTION;
