const QUESTION_CV = {
  OVERALL_CONDITION: {
    DOES_THE_UNIT_HAVE_TWO_KEYS_WITH_FOBS_AVAILABLE: 1,
    IS_THE_UNIT_EXTERIOR_CLEAN: 2,
    IS_THE_INTERIOR_FREE_OF_STRONG_ODORS: 2,
    IS_THE_UNIT_INTERIOR_CLEAN_AND_FREE_OF_RUBBISH: 1,
  },
  DRIVER_DOOR: {
    IS_DOOR_OPERATIONAL: 1,
    IS_DOOR_FRAME_FREE_OF_CRACKS_AT_HINGE_OR_OTHER_ATTACHMENT_POINT: 1,
    IS_DOOR_STRAP_INTACT: 1,
  },
  DRIVER_MIRROR: { IS_THE_MARKER_SIGNAL_LAMP_OPERABLE: 2 },
  HOOD: { DOES_HOOD_OPERATE_FREELY: 2 },
  LIGHTS: {
    DO_HEADLIGHTS_ILLUMINATE: 2,
    DO_MARKER_LIGHTS_ILLUMINATE: 1,
  },
  BUMPER: { IS_LICENSE_PLATE_INSTALLED_IF_APPLICABLE: 1 },
  PASSENGER_MIRROR: { IS_THE_MARKER_SIGNAL_LAMP_OPERABLE: 1 },
  PASSENGER_DOOR_EXTERIOUR: {
    IS_DOOR_OPERATIONAL: 1,
    IS_DOOR_FRAME_FREE_OF_CRACKS_AT_HINGE_OR_OTHER_ATTACHMENT_POINT: 1,
    IS_DOOR_STRAP_INTACT_RAM_ONLY: 1,
  },
  RH_CARGO_DOOR: {
    DOES_THE_DOOR_OPERATE_SMOOTHLY_AND_CORRECT__CV_ONLY: 1,
  },
  STEP: {
    IS_THE_RH_STEP_PRESENT_CV_ONLY: 2,
    IS_THE_STEP_FREE_FROM_DAMAGE_CV_ONLY: 2,
    ARE_THE_STEP_END_CAPS_INTACT_CV_ONLY: 2,
  },
  RH_BODY_PANEL: { IS_THE_AMAZON_BRANDING_FREE_OF_DAMAGE: 1 },
  RH_REAR_DOOR: {
    IS_DOOR_OPERATIONAL_CV_ONLY: 2,
    IS_DOOR_FRAME_FREE_OF_CRACKS_AT_HINGE_OR_OTHER_ATTACHMENT_POINT_CV_ONLY: 1,
    IS_DOOR_STRAP_INTACT_CV_ONLY: 2,
  },
  LH_REAR_DOOR: {
    IS_DOOR_OPERATIONAL_CV_ONLY: 1,
    IS_DOOR_FRAME_FREE_OF_CRACKS_AT_HINGE_OR_OTHER_ATTACHMENT_POINT_CV_ONLY: 1,
    IS_DOOR_STRAP_INTACT_CV_ONLY: 1,
  },
  ROLLUP_DOOR: { IS_DOOR_OPERATIONAL_CV_CDV_ONLY: 1 },
  TAIL_LIGHTS: { ARE_THE_BULBS_OPERATIONAL: 1 },
  REAR_STEP: {
    IS_THE_RH_STEP_PRESENT: 1,
    IS_THE_STEP_FREE_FROM_DAMAGE: 2,
    ARE_THE_STEP_END_CAPS_INTACT: 2,
  },
  SPARE_TIRE: { IS_THE_SPARE_TIRE_PRESENT_CV_ONLY: 1 },
  LICENSE_PLATE: { IS_LICENSE_PLATE_INSTALLED: 1 },
  DRIVER_COCKPIT: {
    DOES_VEHICLE_START: 1,
    IS_THE_VEHICLE_RUNNING_SMOOTHLY: 2,
    IS_THE_DASHBOARD_FREE_OF_ANY_WARNING_LIGHTS: 2,
    IS_INSTRUMENT_CLUSTER_FREE_OF_DAMAGE: 2,
    IS_STEERING_WHEEL_FREE_OF_DAMAGE: 2,
    IS_PARKING_BRAKE_OPERATIONAL: 2,
    IS_THE_REAR_VIEW_CAMERA_OPERATIONAL: 1,
    IS_THE_NETRADYNECAMERATELEMATICS_DEVICE_SECURE: 1,
    IS_SEAT_BELT_FREE_OF_DAMAGE: 1,
    DOES_SEAT_BELT_PROPERLY_BUCKLE: 1,
    IS_DRIVER_SEAT_FREE_OF_DAMAGE: 1,
    IS_AREA_CLEAN: 2,
    IS_VEHICLE_REGISTRATION_IN_VEHICLE: 2,
    IS_SAFETY_KIT_PRESENT: 2,
  },
  PASSENGER_AREA: {
    IS_SEAT_BELT_FREE_OF_DAMAGE: 2,
    DOES_SEAT_BELT_PROPERLY_BUCKLE: 2,
    IS_DRIVER_SEAT_FREE_OF_DAMAGE: 2,
    IS_AREA_CLEAN: 1,
    ARE_THE_INTERIORS_FREE_OF_ANY_OBVIOUS_DAMAGE: 1,
    IS_THE_CABIN_FREE_OF_ANY_SMOKE_ODORS: 1,
  },
  DIVIDER_DOOR: {
    IS_THE_DIVIDER_DOOR_OPERATIONAL: 1,
    DOES_THE_DOOR_LATCH_OPEN: 1,
    DOES_THE_DOOR_LATCH_CLOSE: 1,
  },
  CARGO_AREA: {
    ARE_CARGO_SHELVES_PRESENT: 1,
    IS_THE_CARGO_AREA_FREE_OF_DAMAGE: 1,
    IS_THE_AREA_CLEAN: 1,
    ARE_INTERIOR_LIGHTS_OPERATIONAL: 2,
    IS_WHEEL_DOLLY_PRESENT: 2,
  },
  FRAME__STRUCTURAL__UNIBODY: {
    IS_THE_STRUCTURE_OR_UNIBODY_FREE_OF_ANY_OBVIOUS_DAMAGE: 2,
  },
  EXHAUST_SYSTEM: {
    IS_THE_EXHAUST_SYSTEM_FREE_ANY_EXHAUST_LEAKS_OR_DAMAGE: 2,
  },
  ENGINE_OR_MECHANICAL_DAMAGE: {
    IS_THE_ENGINE_FREE_OF_ANY_MECHANICAL_DAMAGES: 2,
  },
  ELECTRICAL: {
    ARE_ALL_THE_ELECTRICAL_EQUIPMENT_AND_ACCESSORIES_OPERABLE: 1,
  },
};

export default QUESTION_CV